# **Numpy**: **Num**erical **Py**thon
### Notes By: *Arnav*

##### Abstract: This notebook is made on Jupyter-Notebook in IPython Kernel Detailing about Python Library "Numpy" possessing multiple source including [W3School](https://www.w3schools.com/python/numpy)

Short Notes:
1. np.arange
2. ndarray.reshape

#### Basic Importing, ALiasing and Display

In [1]:
import numpy as np

In [2]:
ls_a=[[2,3,5,3],[4,5,9,5],[7,9,8,1]]
a=np.array(ls_a)
print(a)
print(type(a))

[[2 3 5 3]
 [4 5 9 5]
 [7 9 8 1]]
<class 'numpy.ndarray'>


#### Common Attributes of class 'numpy.ndarray':

In [3]:
a=np.array([[2,3,5,3],[4,5,9,5],[7,9,8,1]])
print("Dimension:\t",a.ndim)
print("Shape:\t\t",a.shape)
print("Size:\t\t",a.size)
print("DataType:\t",a.dtype)
print("ItemSize:\t",a.itemsize)
print("Data:\t\t",a.data)
print("Flat Array:\t\t",np.array(a.flat))
print('\n'+'#'*50+'\n')


Dimension:	 2
Shape:		 (3, 4)
Size:		 12
DataType:	 int64
ItemSize:	 8
Data:		 <memory at 0x000001CFA4532A80>
Flat Array:		 [2 3 5 3 4 5 9 5 7 9 8 1]

##################################################



#### Array Creation

In [4]:
print(
    np.array([(1.5, 2, 3), (4, 5, 6)], dtype='float64'),
    np.zeros((3, 4)),
    np.zeros((3, 4)),
    np.empty((2, 3)),
    np.arange(10, 30, 5),
    np.arange(10).reshape(2,5),
    np.linspace(0, 2, 9),
    
sep='\n\n')

[[1.5 2.  3. ]
 [4.  5.  6. ]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[3.33772792e-307 4.22786102e-307 3.44899350e-307]
 [2.44774252e-307 3.44900708e-307 9.94648370e+086]]

[10 15 20 25]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### Array Printing Options
```python
np.set_printoptions(precision=None, suppress=None, threshold=None, linewidth=None, formatter=None)
np.set_printoptions(threshold=sys.maxsize)#Prints whole array instead of ... out the large arrays
```


#### Array Operations

In [5]:
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 7],
              [3, 4]])

print(
    a-b,
    a+b**3,
    a*np.sin(b),
    a/b,
    a@b,
    a.dot(b),
    # More operators Available
sep='\n\n')

[[-1 -6]
 [-3 -3]]

[[  9 344]
 [ 27  65]]

[[ 0.90929743  0.6569866 ]
 [ 0.         -0.7568025 ]]

[[0.5        0.14285714]
 [0.         0.25      ]]

[[ 5 11]
 [ 3  4]]

[[ 5 11]
 [ 3  4]]


In [6]:
print(f"Before:\na=\n{a}\nb=\n{b}")
a *= b
# More operators Available
print(f"\nAfter:\na=\n{a}\nb=\n{b}")

Before:
a=
[[1 1]
 [0 1]]
b=
[[2 7]
 [3 4]]

After:
a=
[[2 7]
 [0 4]]
b=
[[2 7]
 [3 4]]


#### Universal Functions (ufunc)

In [7]:
a=np.arange(3)
print(a)
print(np.exp(a))
print(np.sqrt(a))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


#### Indexing Slicing

In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1, 2], '\n')#Basic Indexing
print(arr[0:2, 1:3], '\n')#Slicing
print(arr[arr > 50], '\n')#Boolean Indexing
indices = [0, 2];print(arr[indices], '\n')#Fancy Indexing
print(arr[[0, 2]], '\n')# Access specific rows
print(arr[:, [0, 2]], '\n')# Access specific columns

60 

[[20 30]
 [50 60]] 

[60 70 80 90] 

[[10 20 30]
 [70 80 90]] 

[[10 20 30]
 [70 80 90]] 

[[10 30]
 [40 60]
 [70 90]] 



#### Iteration

In [9]:
for row in arr:
    print(row)

[10 20 30]
[40 50 60]
[70 80 90]


In [10]:
for i in arr.flat:
    print(i, end='\t')
    
print()

for element in np.nditer(arr,op_flags=['readwrite'],order='F'):
    print(element, end='\t')

print()

for i in range(arr.shape[0]):  # iterate over rows
    for j in range(arr.shape[1]):  # iterate over columns
        print(arr[i, j], end='\t')

10	20	30	40	50	60	70	80	90	
10	40	70	20	50	80	30	60	90	
10	20	30	40	50	60	70	80	90	

In [11]:
for index, element in np.ndenumerate(arr):
    print(index, element,end='\t')

print()

for index in np.ndindex(arr.shape):
    print(index, arr[index],end='\t')

print('\n')

(0, 0) 10	(0, 1) 20	(0, 2) 30	(1, 0) 40	(1, 1) 50	(1, 2) 60	(2, 0) 70	(2, 1) 80	(2, 2) 90	
(0, 0) 10	(0, 1) 20	(0, 2) 30	(1, 0) 40	(1, 1) 50	(1, 2) 60	(2, 0) 70	(2, 1) 80	(2, 2) 90	



In [12]:
vec_square = np.vectorize(lambda x:x**2)
print(vec_square(arr))

[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]


In [13]:
for index, value in enumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: [10 20 30]
Index: 1, Value: [40 50 60]
Index: 2, Value: [70 80 90]
