# **Numpy**: **Num**erical **Py**thon
### Notes By: *Arnav*

##### Abstract: This notebook is made on Jupyter-Notebook in IPython Kernel Detailing about Python Library "Numpy" possessing multiple source including [W3School](https://www.w3schools.com/python/numpy)

### Basic Importing, Aliasing and Display

In [1]:
import numpy as np

In [2]:
ls_a=[[2,3,5,3],[4,5,9,5],[7,9,8,1]]
a=np.array(ls_a)
print(a)
print(type(a))

[[2 3 5 3]
 [4 5 9 5]
 [7 9 8 1]]
<class 'numpy.ndarray'>


### Common Attributes of class 'numpy.ndarray':

In [3]:
a=np.array([[2,3,5,3],[4,5,9,5],[7,9,8,1]])
print("Dimension:\t",a.ndim)
print("Shape:\t\t",a.shape)
print("Size:\t\t",a.size)
print("DataType:\t",a.dtype)
print("ItemSize:\t",a.itemsize)
print("Data:\t\t",a.data)
print("Flat Array:\t\t",np.array(a.flat))
print('\n'+'#'*50+'\n')


Dimension:	 2
Shape:		 (3, 4)
Size:		 12
DataType:	 int64
ItemSize:	 8
Data:		 <memory at 0x00000248336F3C60>
Flat Array:		 [2 3 5 3 4 5 9 5 7 9 8 1]

##################################################



### Array Creation

In [4]:
print(np.array([(1.5, 2, 3), (4, 5, 6)], dtype='float64'))

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [5]:
print(
    np.zeros((3, 4)),
    np.ones((3, 4)),
    np.identity(3),
    np.empty((2, 3)),
    np.empty_like([(1.5, 2, 3), (4, 5, 6)]),#np.ones_like and np.zeros_like also exists
sep='\n\n')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1.5 2.  3. ]
 [4.  5.  6. ]]

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [6]:
print(
    np.arange(10, 30, 5),
    np.arange(10).reshape(2,5),
    np.linspace(0, 2, 9, dtype=float),
    np.logspace(0,3,50,base=2, dtype=int),
sep='\n\n')

[10 15 20 25]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 4 4 4 4
 4 5 5 5 5 5 6 6 6 7 7 7 8]


In [7]:
print(np.fromfunction(lambda i, j: i + j, (3, 3), dtype='float32'))

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


#### ~Functions~ Indexing Objects:
- np.mgrid[]
- np.ogrid[]
- np.r_[]

np.r_ is a powerful and flexible tool for combining arrays and creating sequences in a concise way. It can be particularly useful for quick prototyping or when writing one-liners to generate or concatenate arrays.

In [8]:
print(
    np.mgrid[0:6:2j, 0:4:1],
    np.ogrid[0:6:2j, 0:4:1],
sep='\n\n\n',end='\n\n\n')

[[[0. 0. 0. 0.]
  [6. 6. 6. 6.]]

 [[0. 1. 2. 3.]
  [0. 1. 2. 3.]]]


(array([[0.],
       [6.]]), array([[0., 1., 2., 3.]]))




In [9]:
np.r_[np.array([[1,2],[3,4]]),np.array([[5,6],[7,8]])]#Equivalent to np.concatenate

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
print(np.r_[0:10:1]) # Equivalent to np.arange(0, 10, 1)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(np.r_[0:10:5j])# Equivalent to np.linspace(0, 10, 5)

[ 0.   2.5  5.   7.5 10. ]


### Array Printing Options
```python
np.set_printoptions(precision=None, suppress=None, threshold=None, linewidth=None, formatter=None)
np.set_printoptions(threshold=sys.maxsize)#Prints whole array instead of '...' out the large arrays
print(np.get_printoptions())
```


In [12]:
#For printing simply use as mentioned 'print(np.ndarray)'

### Array Operations

In [13]:
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 7],
              [3, 4]])

print(a*5,end='\n\n')#operation between a vector and a scalar is called broadcasting
print(
    a-b,
    a+b**3,
    a*np.sin(b),
    a/b,
    a@b,
    a.dot(b),
    # More operators Available
sep='\n\n')

[[5 5]
 [0 5]]

[[-1 -6]
 [-3 -3]]

[[  9 344]
 [ 27  65]]

[[ 0.90929743  0.6569866 ]
 [ 0.         -0.7568025 ]]

[[0.5        0.14285714]
 [0.         0.25      ]]

[[ 5 11]
 [ 3  4]]

[[ 5 11]
 [ 3  4]]


In [14]:
print(f"Before:\na=\n{a}\nb=\n{b}")
a *= b
# More operators Available
print(f"\nAfter:\na=\n{a}\nb=\n{b}")

Before:
a=
[[1 1]
 [0 1]]
b=
[[2 7]
 [3 4]]

After:
a=
[[2 7]
 [0 4]]
b=
[[2 7]
 [3 4]]


### Universal Functions (ufunc)

In [15]:
a=np.arange(3)
print(a)
print(np.exp(a))
print(np.sqrt(a))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


#### Ufunc Table

<h5>Math operations<a class="headerlink" href="#math-operations" title="Link to this heading">#</a></h5>

<section id="math-operations">
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.add.html#numpy.add" title="numpy.add"><code class="xref py py-obj docutils literal notranslate"><span class="pre">add</span></code></a>(x1, x2, /[, out, where, casting, order, ...])</p></td>
<td><p>Add arguments element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.subtract.html#numpy.subtract" title="numpy.subtract"><code class="xref py py-obj docutils literal notranslate"><span class="pre">subtract</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Subtract arguments, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.multiply.html#numpy.multiply" title="numpy.multiply"><code class="xref py py-obj docutils literal notranslate"><span class="pre">multiply</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Multiply arguments element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.matmul.html#numpy.matmul" title="numpy.matmul"><code class="xref py py-obj docutils literal notranslate"><span class="pre">matmul</span></code></a>(x1, x2, /[, out, casting, order, ...])</p></td>
<td><p>Matrix product of two arrays.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.divide.html#numpy.divide" title="numpy.divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">divide</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Divide arguments element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.logaddexp.html#numpy.logaddexp" title="numpy.logaddexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logaddexp</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Logarithm of the sum of exponentiations of the inputs.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.logaddexp2.html#numpy.logaddexp2" title="numpy.logaddexp2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logaddexp2</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Logarithm of the sum of exponentiations of the inputs in base-2.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.true_divide.html#numpy.true_divide" title="numpy.true_divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">true_divide</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Divide arguments element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.floor_divide.html#numpy.floor_divide" title="numpy.floor_divide"><code class="xref py py-obj docutils literal notranslate"><span class="pre">floor_divide</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Return the largest integer smaller or equal to the division of the inputs.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.negative.html#numpy.negative" title="numpy.negative"><code class="xref py py-obj docutils literal notranslate"><span class="pre">negative</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Numerical negative, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.positive.html#numpy.positive" title="numpy.positive"><code class="xref py py-obj docutils literal notranslate"><span class="pre">positive</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Numerical positive, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.power.html#numpy.power" title="numpy.power"><code class="xref py py-obj docutils literal notranslate"><span class="pre">power</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>First array elements raised to powers from second array, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.float_power.html#numpy.float_power" title="numpy.float_power"><code class="xref py py-obj docutils literal notranslate"><span class="pre">float_power</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>First array elements raised to powers from second array, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.remainder.html#numpy.remainder" title="numpy.remainder"><code class="xref py py-obj docutils literal notranslate"><span class="pre">remainder</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Returns the element-wise remainder of division.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.mod.html#numpy.mod" title="numpy.mod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">mod</span></code></a>(x1, x2, /[, out, where, casting, order, ...])</p></td>
<td><p>Returns the element-wise remainder of division.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.fmod.html#numpy.fmod" title="numpy.fmod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmod</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Returns the element-wise remainder of division.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.divmod.html#numpy.divmod" title="numpy.divmod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">divmod</span></code></a>(x1, x2[, out1, out2], / [[, out, ...])</p></td>
<td><p>Return element-wise quotient and remainder simultaneously.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.absolute.html#numpy.absolute" title="numpy.absolute"><code class="xref py py-obj docutils literal notranslate"><span class="pre">absolute</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Calculate the absolute value element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.fabs.html#numpy.fabs" title="numpy.fabs"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fabs</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Compute the absolute values element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.rint.html#numpy.rint" title="numpy.rint"><code class="xref py py-obj docutils literal notranslate"><span class="pre">rint</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Round elements of the array to the nearest integer.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.sign.html#numpy.sign" title="numpy.sign"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sign</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Returns an element-wise indication of the sign of a number.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.heaviside.html#numpy.heaviside" title="numpy.heaviside"><code class="xref py py-obj docutils literal notranslate"><span class="pre">heaviside</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Compute the Heaviside step function.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.conj.html#numpy.conj" title="numpy.conj"><code class="xref py py-obj docutils literal notranslate"><span class="pre">conj</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the complex conjugate, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.conjugate.html#numpy.conjugate" title="numpy.conjugate"><code class="xref py py-obj docutils literal notranslate"><span class="pre">conjugate</span></code></a>(x, /[, out, where, casting, ...])</p></td>
<td><p>Return the complex conjugate, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.exp.html#numpy.exp" title="numpy.exp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">exp</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Calculate the exponential of all elements in the input array.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.exp2.html#numpy.exp2" title="numpy.exp2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">exp2</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Calculate <em class="xref py py-obj">2**p</em> for all <em class="xref py py-obj">p</em> in the input array.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.log.html#numpy.log" title="numpy.log"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Natural logarithm, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.log2.html#numpy.log2" title="numpy.log2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log2</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Base-2 logarithm of <em class="xref py py-obj">x</em>.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.log10.html#numpy.log10" title="numpy.log10"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log10</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the base 10 logarithm of the input array, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.expm1.html#numpy.expm1" title="numpy.expm1"><code class="xref py py-obj docutils literal notranslate"><span class="pre">expm1</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Calculate <code class="docutils literal notranslate"><span class="pre">exp(x)</span> <span class="pre">-</span> <span class="pre">1</span></code> for all elements in the array.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.log1p.html#numpy.log1p" title="numpy.log1p"><code class="xref py py-obj docutils literal notranslate"><span class="pre">log1p</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the natural logarithm of one plus the input array, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.sqrt.html#numpy.sqrt" title="numpy.sqrt"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sqrt</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the non-negative square-root of an array, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.square.html#numpy.square" title="numpy.square"><code class="xref py py-obj docutils literal notranslate"><span class="pre">square</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the element-wise square of the input.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.cbrt.html#numpy.cbrt" title="numpy.cbrt"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cbrt</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the cube-root of an array, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.reciprocal.html#numpy.reciprocal" title="numpy.reciprocal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">reciprocal</span></code></a>(x, /[, out, where, casting, ...])</p></td>
<td><p>Return the reciprocal of the argument, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.gcd.html#numpy.gcd" title="numpy.gcd"><code class="xref py py-obj docutils literal notranslate"><span class="pre">gcd</span></code></a>(x1, x2, /[, out, where, casting, order, ...])</p></td>
<td><p>Returns the greatest common divisor of <code class="docutils literal notranslate"><span class="pre">|x1|</span></code> and <code class="docutils literal notranslate"><span class="pre">|x2|</span></code></p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.lcm.html#numpy.lcm" title="numpy.lcm"><code class="xref py py-obj docutils literal notranslate"><span class="pre">lcm</span></code></a>(x1, x2, /[, out, where, casting, order, ...])</p></td>
<td><p>Returns the lowest common multiple of <code class="docutils literal notranslate"><span class="pre">|x1|</span></code> and <code class="docutils literal notranslate"><span class="pre">|x2|</span></code></p></td>
</tr>
</tbody>
</table>
</div>
<div class="admonition tip">
<p class="admonition-title">Tip</p>
<p>The optional output arguments can be used to help you save memory
for large calculations. If your arrays are large, complicated
expressions can take longer than absolutely necessary due to the
creation and (later) destruction of temporary calculation
spaces. For example, the expression <code class="docutils literal notranslate"><span class="pre">G</span> <span class="pre">=</span> <span class="pre">A</span> <span class="pre">*</span> <span class="pre">B</span> <span class="pre">+</span> <span class="pre">C</span></code> is equivalent to
<code class="docutils literal notranslate"><span class="pre">T1</span> <span class="pre">=</span> <span class="pre">A</span> <span class="pre">*</span> <span class="pre">B;</span> <span class="pre">G</span> <span class="pre">=</span> <span class="pre">T1</span> <span class="pre">+</span> <span class="pre">C;</span> <span class="pre">del</span> <span class="pre">T1</span></code>. It will be more quickly executed
as <code class="docutils literal notranslate"><span class="pre">G</span> <span class="pre">=</span> <span class="pre">A</span> <span class="pre">*</span> <span class="pre">B;</span> <span class="pre">add(G,</span> <span class="pre">C,</span> <span class="pre">G)</span></code> which is the same as
<code class="docutils literal notranslate"><span class="pre">G</span> <span class="pre">=</span> <span class="pre">A</span> <span class="pre">*</span> <span class="pre">B;</span> <span class="pre">G</span> <span class="pre">+=</span> <span class="pre">C</span></code>.</p>
</div>
</section>

<h5>Trigonometric functions<a class="headerlink" href="#trigonometric-functions" title="Link to this heading">#</a></h5>

<section id="trigonometric-functions">
<p>All trigonometric functions use radians when an angle is called for.
The ratio of degrees to radians is <span class="math notranslate nohighlight">\(180^{\circ}/\pi.\)</span></p>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.sin.html#numpy.sin" title="numpy.sin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sin</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Trigonometric sine, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.cos.html#numpy.cos" title="numpy.cos"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cos</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Cosine element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.tan.html#numpy.tan" title="numpy.tan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">tan</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Compute tangent element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.arcsin.html#numpy.arcsin" title="numpy.arcsin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arcsin</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Inverse sine, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.arccos.html#numpy.arccos" title="numpy.arccos"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arccos</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Trigonometric inverse cosine, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.arctan.html#numpy.arctan" title="numpy.arctan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctan</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Trigonometric inverse tangent, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.arctan2.html#numpy.arctan2" title="numpy.arctan2"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctan2</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Element-wise arc tangent of <code class="docutils literal notranslate"><span class="pre">x1/x2</span></code> choosing the quadrant correctly.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.hypot.html#numpy.hypot" title="numpy.hypot"><code class="xref py py-obj docutils literal notranslate"><span class="pre">hypot</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Given the &quot;legs&quot; of a right triangle, return its hypotenuse.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.sinh.html#numpy.sinh" title="numpy.sinh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">sinh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Hyperbolic sine, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.cosh.html#numpy.cosh" title="numpy.cosh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">cosh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Hyperbolic cosine, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.tanh.html#numpy.tanh" title="numpy.tanh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">tanh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Compute hyperbolic tangent element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.arcsinh.html#numpy.arcsinh" title="numpy.arcsinh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arcsinh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Inverse hyperbolic sine element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.arccosh.html#numpy.arccosh" title="numpy.arccosh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arccosh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Inverse hyperbolic cosine, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.arctanh.html#numpy.arctanh" title="numpy.arctanh"><code class="xref py py-obj docutils literal notranslate"><span class="pre">arctanh</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Inverse hyperbolic tangent element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.degrees.html#numpy.degrees" title="numpy.degrees"><code class="xref py py-obj docutils literal notranslate"><span class="pre">degrees</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Convert angles from radians to degrees.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.radians.html#numpy.radians" title="numpy.radians"><code class="xref py py-obj docutils literal notranslate"><span class="pre">radians</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Convert angles from degrees to radians.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.deg2rad.html#numpy.deg2rad" title="numpy.deg2rad"><code class="xref py py-obj docutils literal notranslate"><span class="pre">deg2rad</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Convert angles from degrees to radians.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.rad2deg.html#numpy.rad2deg" title="numpy.rad2deg"><code class="xref py py-obj docutils literal notranslate"><span class="pre">rad2deg</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Convert angles from radians to degrees.</p></td>
</tr>
</tbody>
</table>
</div>
</section>

<h5>Bit-twiddling functions<a class="headerlink" href="#bit-twiddling-functions" title="Link to this heading">#</a></h5>

<section id="bit-twiddling-functions">
<p>These function all require integer arguments and they manipulate the
bit-pattern of those arguments.</p>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.bitwise_and.html#numpy.bitwise_and" title="numpy.bitwise_and"><code class="xref py py-obj docutils literal notranslate"><span class="pre">bitwise_and</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Compute the bit-wise AND of two arrays element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.bitwise_or.html#numpy.bitwise_or" title="numpy.bitwise_or"><code class="xref py py-obj docutils literal notranslate"><span class="pre">bitwise_or</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Compute the bit-wise OR of two arrays element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.bitwise_xor.html#numpy.bitwise_xor" title="numpy.bitwise_xor"><code class="xref py py-obj docutils literal notranslate"><span class="pre">bitwise_xor</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Compute the bit-wise XOR of two arrays element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.invert.html#numpy.invert" title="numpy.invert"><code class="xref py py-obj docutils literal notranslate"><span class="pre">invert</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Compute bit-wise inversion, or bit-wise NOT, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.left_shift.html#numpy.left_shift" title="numpy.left_shift"><code class="xref py py-obj docutils literal notranslate"><span class="pre">left_shift</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Shift the bits of an integer to the left.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.right_shift.html#numpy.right_shift" title="numpy.right_shift"><code class="xref py py-obj docutils literal notranslate"><span class="pre">right_shift</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Shift the bits of an integer to the right.</p></td>
</tr>
</tbody>
</table>
</div>
</section>

<h5>Comparison functions<a class="headerlink" href="#comparison-functions" title="Link to this heading">#</a></h5>

<section id="comparison-functions">
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.greater.html#numpy.greater" title="numpy.greater"><code class="xref py py-obj docutils literal notranslate"><span class="pre">greater</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return the truth value of (x1 &gt; x2) element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.greater_equal.html#numpy.greater_equal" title="numpy.greater_equal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">greater_equal</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Return the truth value of (x1 &gt;= x2) element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.less.html#numpy.less" title="numpy.less"><code class="xref py py-obj docutils literal notranslate"><span class="pre">less</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return the truth value of (x1 &lt; x2) element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.less_equal.html#numpy.less_equal" title="numpy.less_equal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">less_equal</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return the truth value of (x1 &lt;= x2) element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.not_equal.html#numpy.not_equal" title="numpy.not_equal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">not_equal</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return (x1 != x2) element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.equal.html#numpy.equal" title="numpy.equal"><code class="xref py py-obj docutils literal notranslate"><span class="pre">equal</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return (x1 == x2) element-wise.</p></td>
</tr>
</tbody>
</table>
</div>
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>Do not use the Python keywords <code class="docutils literal notranslate"><span class="pre">and</span></code> and <code class="docutils literal notranslate"><span class="pre">or</span></code> to combine
logical array expressions. These keywords will test the truth
value of the entire array (not element-by-element as you might
expect). Use the bitwise operators &amp; and | instead.</p>
</div>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.logical_and.html#numpy.logical_and" title="numpy.logical_and"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logical_and</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Compute the truth value of x1 AND x2 element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.logical_or.html#numpy.logical_or" title="numpy.logical_or"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logical_or</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Compute the truth value of x1 OR x2 element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.logical_xor.html#numpy.logical_xor" title="numpy.logical_xor"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logical_xor</span></code></a>(x1, x2, /[, out, where, ...])</p></td>
<td><p>Compute the truth value of x1 XOR x2, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.logical_not.html#numpy.logical_not" title="numpy.logical_not"><code class="xref py py-obj docutils literal notranslate"><span class="pre">logical_not</span></code></a>(x, /[, out, where, casting, ...])</p></td>
<td><p>Compute the truth value of NOT x element-wise.</p></td>
</tr>
</tbody>
</table>
</div>
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>The bit-wise operators &amp; and | are the proper way to perform
element-by-element array comparisons. Be sure you understand the
operator precedence: <code class="docutils literal notranslate"><span class="pre">(a</span> <span class="pre">&gt;</span> <span class="pre">2)</span> <span class="pre">&amp;</span> <span class="pre">(a</span> <span class="pre">&lt;</span> <span class="pre">5)</span></code> is the proper syntax because
<code class="docutils literal notranslate"><span class="pre">a</span> <span class="pre">&gt;</span> <span class="pre">2</span> <span class="pre">&amp;</span> <span class="pre">a</span> <span class="pre">&lt;</span> <span class="pre">5</span></code> will result in an error due to the fact that <code class="docutils literal notranslate"><span class="pre">2</span> <span class="pre">&amp;</span> <span class="pre">a</span></code>
is evaluated first.</p>
</div>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.maximum.html#numpy.maximum" title="numpy.maximum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">maximum</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Element-wise maximum of array elements.</p></td>
</tr>
</tbody>
</table>
</div>
<div class="admonition tip">
<p class="admonition-title">Tip</p>
<p>The Python function <code class="docutils literal notranslate"><span class="pre">max()</span></code> will find the maximum over a one-dimensional
array, but it will do so using a slower sequence interface. The reduce
method of the maximum ufunc is much faster. Also, the <code class="docutils literal notranslate"><span class="pre">max()</span></code> method
will not give answers you might expect for arrays with greater than
one dimension. The reduce method of minimum also allows you to compute
a total minimum over an array.</p>
</div>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.minimum.html#numpy.minimum" title="numpy.minimum"><code class="xref py py-obj docutils literal notranslate"><span class="pre">minimum</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Element-wise minimum of array elements.</p></td>
</tr>
</tbody>
</table>
</div>
<div class="admonition warning">
<p class="admonition-title">Warning</p>
<p>the behavior of <code class="docutils literal notranslate"><span class="pre">maximum(a,</span> <span class="pre">b)</span></code> is different than that of <code class="docutils literal notranslate"><span class="pre">max(a,</span> <span class="pre">b)</span></code>.
As a ufunc, <code class="docutils literal notranslate"><span class="pre">maximum(a,</span> <span class="pre">b)</span></code> performs an element-by-element comparison
of <em class="xref py py-obj">a</em> and <em class="xref py py-obj">b</em> and chooses each element of the result according to which
element in the two arrays is larger. In contrast, <code class="docutils literal notranslate"><span class="pre">max(a,</span> <span class="pre">b)</span></code> treats
the objects <em class="xref py py-obj">a</em> and <em class="xref py py-obj">b</em> as a whole, looks at the (total) truth value of
<code class="docutils literal notranslate"><span class="pre">a</span> <span class="pre">&gt;</span> <span class="pre">b</span></code> and uses it to return either <em class="xref py py-obj">a</em> or <em class="xref py py-obj">b</em> (as a whole). A similar
difference exists between <code class="docutils literal notranslate"><span class="pre">minimum(a,</span> <span class="pre">b)</span></code> and <code class="docutils literal notranslate"><span class="pre">min(a,</span> <span class="pre">b)</span></code>.</p>
</div>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.fmax.html#numpy.fmax" title="numpy.fmax"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmax</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Element-wise maximum of array elements.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.fmin.html#numpy.fmin" title="numpy.fmin"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmin</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Element-wise minimum of array elements.</p></td>
</tr>
</tbody>
</table>
</div>
</section>

<h5>Floating functions<a class="headerlink" href="#floating-functions" title="Link to this heading">#</a></h5>

<section id="floating-functions">
<p>Recall that all of these functions work element-by-element over an
array, returning an array output. The description details only a
single operation.</p>
<div class="pst-scrollable-table-container"><table class="autosummary longtable table autosummary">
<tbody>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.isfinite.html#numpy.isfinite" title="numpy.isfinite"><code class="xref py py-obj docutils literal notranslate"><span class="pre">isfinite</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Test element-wise for finiteness (not infinity and not Not a Number).</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.isinf.html#numpy.isinf" title="numpy.isinf"><code class="xref py py-obj docutils literal notranslate"><span class="pre">isinf</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Test element-wise for positive or negative infinity.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.isnan.html#numpy.isnan" title="numpy.isnan"><code class="xref py py-obj docutils literal notranslate"><span class="pre">isnan</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Test element-wise for NaN and return result as a boolean array.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.isnat.html#numpy.isnat" title="numpy.isnat"><code class="xref py py-obj docutils literal notranslate"><span class="pre">isnat</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Test element-wise for NaT (not a time) and return result as a boolean array.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.fabs.html#numpy.fabs" title="numpy.fabs"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fabs</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Compute the absolute values element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.signbit.html#numpy.signbit" title="numpy.signbit"><code class="xref py py-obj docutils literal notranslate"><span class="pre">signbit</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Returns element-wise True where signbit is set (less than zero).</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.copysign.html#numpy.copysign" title="numpy.copysign"><code class="xref py py-obj docutils literal notranslate"><span class="pre">copysign</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Change the sign of x1 to that of x2, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.nextafter.html#numpy.nextafter" title="numpy.nextafter"><code class="xref py py-obj docutils literal notranslate"><span class="pre">nextafter</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Return the next floating-point value after x1 towards x2, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.spacing.html#numpy.spacing" title="numpy.spacing"><code class="xref py py-obj docutils literal notranslate"><span class="pre">spacing</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the distance between x and the nearest adjacent number.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.modf.html#numpy.modf" title="numpy.modf"><code class="xref py py-obj docutils literal notranslate"><span class="pre">modf</span></code></a>(x[, out1, out2], / [[, out, where, ...])</p></td>
<td><p>Return the fractional and integral parts of an array, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.ldexp.html#numpy.ldexp" title="numpy.ldexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ldexp</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Returns x1 * 2**x2, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.frexp.html#numpy.frexp" title="numpy.frexp"><code class="xref py py-obj docutils literal notranslate"><span class="pre">frexp</span></code></a>(x[, out1, out2], / [[, out, where, ...])</p></td>
<td><p>Decompose the elements of x into mantissa and twos exponent.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.fmod.html#numpy.fmod" title="numpy.fmod"><code class="xref py py-obj docutils literal notranslate"><span class="pre">fmod</span></code></a>(x1, x2, /[, out, where, casting, ...])</p></td>
<td><p>Returns the element-wise remainder of division.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.floor.html#numpy.floor" title="numpy.floor"><code class="xref py py-obj docutils literal notranslate"><span class="pre">floor</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the floor of the input, element-wise.</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="generated/numpy.ceil.html#numpy.ceil" title="numpy.ceil"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ceil</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the ceiling of the input, element-wise.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="generated/numpy.trunc.html#numpy.trunc" title="numpy.trunc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">trunc</span></code></a>(x, /[, out, where, casting, order, ...])</p></td>
<td><p>Return the truncated value of the input, element-wise.</p></td>
</tr>
</tbody>
</table>
</div>
</section>

#### Ufunc creation

In [16]:
def add_strings(x, y):
    return int(int(x) + int(y))

ufunc = np.frompyfunc(add_strings, 2, 1)
print(ufunc(np.array([2,3]),np.array([5,6])))

[7 9]


### Indexing Slicing

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1, 2], '\n')#Basic Indexing
print(arr[0:2, 1:3], '\n')#Slicing
print(arr[arr > 50], '\n')#Boolean Indexing
indices = [0, 2];print(arr[indices], '\n')#Fancy Indexing
print(arr[[0, 2]], '\n')# Access specific rows
print(arr[:, [0, 2]], '\n')# Access specific columns

60 

[[20 30]
 [50 60]] 

[60 70 80 90] 

[[10 20 30]
 [70 80 90]] 

[[10 20 30]
 [70 80 90]] 

[[10 30]
 [40 60]
 [70 90]] 



### Iteration

In [18]:
for row in arr:
    print(row)

[10 20 30]
[40 50 60]
[70 80 90]


In [19]:
for i in arr.flat:
    print(i, end='\t')
    
print()

for element in np.nditer(arr,op_flags=['readwrite'],order='F'):
    print(element, end='\t')

print()

for i in range(arr.shape[0]):  # iterate over rows
    for j in range(arr.shape[1]):  # iterate over columns
        print(arr[i, j], end='\t')

10	20	30	40	50	60	70	80	90	
10	40	70	20	50	80	30	60	90	
10	20	30	40	50	60	70	80	90	

In [20]:
for index, element in np.ndenumerate(arr):
    print(index, element,end='\t')

print()

for index in np.ndindex(arr.shape):
    print(index, arr[index],end='\t')

print('\n')

(0, 0) 10	(0, 1) 20	(0, 2) 30	(1, 0) 40	(1, 1) 50	(1, 2) 60	(2, 0) 70	(2, 1) 80	(2, 2) 90	
(0, 0) 10	(0, 1) 20	(0, 2) 30	(1, 0) 40	(1, 1) 50	(1, 2) 60	(2, 0) 70	(2, 1) 80	(2, 2) 90	



In [21]:
vec_square = np.vectorize(lambda x:x**2)
print(vec_square(arr))

[[ 100  400  900]
 [1600 2500 3600]
 [4900 6400 8100]]


In [22]:
for index, value in enumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: [10 20 30]
Index: 1, Value: [40 50 60]
Index: 2, Value: [70 80 90]


### Shape Manipulation

#### Array Reshaping

In [23]:
arr=np.arange(30)
print(arr.reshape(6,5))
print('\n\n')
print(arr.reshape((2, -1, 3)))  # -1 means "whatever is needed"
print('\n\n')
print(np.atleast_2d(4,[[[5]]]))#atleast_1d,atleast_3d also exists

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]



(array([[4]]), array([[[5]]]))


#### Array Stacking

In [24]:
a=np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [5,6],
    [7,8]
])

In [25]:
print(np.hstack((a,b)))#a and b are required to have same number of rows

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
print(np.vstack((a, b)))#a and b are required to have same number of columns

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
print(np.dstack((a,b)))#a and b are required to have same SHAPE because stacking is being done in other (here 3rd) axis

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [28]:
print(np.row_stack((a, b)))#Work as vstack; Raises DepracationWarning

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


C:\Users\Hp\AppData\Local\Temp\ipykernel_2096\4011443607.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))#Work as vstack; Raises DepracationWarning


In [29]:
print(np.column_stack((a, b)))# Important # If arrays are 2D then works as np.hstack.
#BUT if both arrays are 1D then considers both arrays as COLUMNS and create a 2D matrix
#UNLIKE np.hstack which in case of 1D arrays returns 1D array with both arrays concatenated

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
# UNLIKE np.stack, This function does not create new dimension
print(np.concatenate((a, b), axis=0))
print('____________\n')
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
____________

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
# UNLIKE np.concatenate, This function creates new dimension
print(np.stack((a, b), axis=0))
print('_____________\n')
print(np.stack((a, b), axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
_____________

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [32]:
print(np.tile(a,reps=5))
#Repeats the array a along each dimension specified by reps. This does not stack arrays per se, but it creates a repeated pattern.

[[1 2 1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4 3 4]]


In [33]:
print(np.repeat(a,5, axis=1))
#Repeats elements in the array along a specified axis. This also doesn’t strictly stack, but it can mimic stacking by repeating arrays.

[[1 1 1 1 1 2 2 2 2 2]
 [3 3 3 3 3 4 4 4 4 4]]


#### Array Splitting

In [34]:
arr1 = np.arange(12)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [35]:
print(np.split(arr1, 4),end='\n\n')# Split the array into 3 equal parts
print(np.split(arr1, 5))# Raises Error due to uneven distribution

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]



ValueError: array split does not result in an equal division

In [ ]:
print(np.array_split(arr1, 5))# similar to np.split(), but it allows splitting an array into unequal parts
print(np.array_split(arr1, 4))

In [ ]:
for i in np.hsplit(arr2,3):
    print(i,end='\n\n')

In [ ]:
for i in np.vsplit(arr2,2):
    print(i,end='\n\n')

In [ ]:
for i in np.dsplit(arr3,2):
    print(i, end='\n\n')

### Questions

In [ ]:
arr=np.array([True,True,False])
print(
    np.all(arr),
    arr.all(),
    np.any(arr),
    arr.any(),
sep='\n')